### ISSUE TITLE
Cannot handle different pixel widths of the inner black border ?

### ISSUE THREAD

**Issue by MaxChanger** [cfneuhaus/fast_mit_apriltags#5]
Hello guys,

In another project, the author used the fast_mit_apriltas library, and then I encountered a strange problem and found the reason.

As the tag images in your `tags` folder, the pixels wide of the inner black border is 1 (This is exactly what I successfully used), but in AprilGrids, which is commonly used for camera or IMU calibration, the pixels wide of the inner black border is 2, so the tag in AprilGrids cannot be detected anyway, unless make inner_black_border = 2.  But I checked the code and did not find the relevant definition about the inner black border.

Is there any suggested solution? 

Thanks.

![tag_and_board](https://user-images.githubusercontent.com/35401968/89114436-e6cfd680-d4ae-11ea-9712-27571ddc7dea.jpg)
> the image source: [link](https://berndpfrommer.github.io/tagslam_web/making_tags/)

**Comment by cfneuhaus** [comment]
Dear Max,
it seems like this parameter is not exposed, but still present in the original code. I would assume that you can change it via the "blackBorder"-member in the TagFamily class. You can change it in line 30 of TagFamily.cpp (see [here](https://github.com/cfneuhaus/fast_mit_apriltags/blob/5d5129ffda1af45982fcfb1fbe438176b72f41a8/src/TagFamily.cc#L30)).

Let me know if this helps!

**Comment by MaxChanger** [comment]
Yeah, It makes sense to modify this parameter in line30 `blackBorder(1)` --> ` blackBorder(2)`.

But it seems that pass in a parameter is better, it will takes me some time, but it doesn’t matter, I’m glad to get your help.

Thanks again.

![Screenshot from 2020-08-02 14-48-54](https://user-images.githubusercontent.com/35401968/89117414-29ee7180-d4d0-11ea-9fe6-c674741da899.png)
